
version: '3.5'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
       - postgres:/data/postgres
#    ports:
#      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  flask:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    flask: