
version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA
      - POSTGRES_DB
    volumes:
       - postgres:/data/postgres
#    ports:
#      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  flask:
    image: kishinskiy/myflask:latest
    environment:
      - PORT
      - DB
      - DEBUG
    ports:
      - $PORT:$PORT
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    flask: