name: flask-app

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v2

      - name: Setup  Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install dev-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry env use python3.9
          poetry install

      - name: test flask-app
        run: |
          poetry run python isort .
          poetry run python flake8 .
